Resources:
  pipelines3bucket60FDE7F2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: codepipeline-builder-microservice-2
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  springeurekagalleryrepoC474C0E2:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: spring-eureka-gallery
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  springeurekaserverrepo1350F586:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: spring-eureka-server
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  springeurekazuulrepo3CAF3D98:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: spring-eureka-zuul
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  springeurekaauthrepo62035FE7:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: spring-eureka-auth
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  microservicebuilderRoleE267C15A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
  microservicebuilderRoleDefaultPolicy0ABB4B92:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicebuilderEA0AB225
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicebuilderEA0AB225
                    - :*
          - Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: microservicebuilderEA0AB225
                  - -*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - pipelines3bucket60FDE7F2
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - pipelines3bucket60FDE7F2
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: microservicebuilderRoleDefaultPolicy0ABB4B92
      Roles:
        - Ref: microservicebuilderRoleE267C15A
  microservicebuilderEA0AB225:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - microservicebuilderRoleE267C15A
          - Arn
      Source:
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      Name: microservice-builder
  ecraccesspolicy1B6F6DE0:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ecr:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ecr-access-policy
      Roles:
        - Ref: microservicebuilderRoleE267C15A
  microservicepipelineRoleEDB68B98:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: "2012-10-17"
  microservicepipelineRoleDefaultPolicyFBAD8A8F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - pipelines3bucket60FDE7F2
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - pipelines3bucket60FDE7F2
                        - Arn
                    - /*
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineBuildCodePipelineActionRole5183B64F
                - Arn
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineDeployCodePipelineActionRole7CFFD997
                - Arn
        Version: "2012-10-17"
      PolicyName: microservicepipelineRoleDefaultPolicyFBAD8A8F
      Roles:
        - Ref: microservicepipelineRoleEDB68B98
  microservicepipelineD3929609:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - microservicepipelineRoleEDB68B98
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: dmytrozzz
                Repo: microservices-spring-boot
                Branch: master
                OAuthToken: 2a3c700993e8b09b24fd32851329065728069c90
                PollForSourceChanges: false
              Name: Source
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: microservicebuilderEA0AB225
                EnvironmentVariables:
                  Fn::Join:
                    - ""
                    - - '[{"name":"AUTH_REPO","type":"PLAINTEXT","value":"'
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekaauthrepo62035FE7
                                  - Arn
                      - .dkr.ecr.
                      - Fn::Select:
                          - 3
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekaauthrepo62035FE7
                                  - Arn
                      - "."
                      - Ref: AWS::URLSuffix
                      - /
                      - Ref: springeurekaauthrepo62035FE7
                      - '"},{"name":"GALLERY_REPO","type":"PLAINTEXT","value":"'
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekagalleryrepoC474C0E2
                                  - Arn
                      - .dkr.ecr.
                      - Fn::Select:
                          - 3
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekagalleryrepoC474C0E2
                                  - Arn
                      - "."
                      - Ref: AWS::URLSuffix
                      - /
                      - Ref: springeurekagalleryrepoC474C0E2
                      - '"},{"name":"EUREKA_REPO","type":"PLAINTEXT","value":"'
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekaserverrepo1350F586
                                  - Arn
                      - .dkr.ecr.
                      - Fn::Select:
                          - 3
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekaserverrepo1350F586
                                  - Arn
                      - "."
                      - Ref: AWS::URLSuffix
                      - /
                      - Ref: springeurekaserverrepo1350F586
                      - '"},{"name":"ZUUL_REPO","type":"PLAINTEXT","value":"'
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekazuulrepo3CAF3D98
                                  - Arn
                      - .dkr.ecr.
                      - Fn::Select:
                          - 3
                          - Fn::Split:
                              - ":"
                              - Fn::GetAtt:
                                  - springeurekazuulrepo3CAF3D98
                                  - Arn
                      - "."
                      - Ref: AWS::URLSuffix
                      - /
                      - Ref: springeurekazuulrepo3CAF3D98
                      - '"}]'
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build
              RoleArn:
                Fn::GetAtt:
                  - microservicepipelineBuildCodePipelineActionRole5183B64F
                  - Arn
              RunOrder: 1
          Name: Build
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: microservicedeployer94899C23
              InputArtifacts:
                - Name: SourceArtifact
              Name: Deploy
              RoleArn:
                Fn::GetAtt:
                  - microservicepipelineDeployCodePipelineActionRole7CFFD997
                  - Arn
              RunOrder: 1
          Name: Deploy
      ArtifactStore:
        Location:
          Ref: pipelines3bucket60FDE7F2
        Type: S3
      Name: microservice-pipeline
    DependsOn:
      - microservicepipelineRoleDefaultPolicyFBAD8A8F
      - microservicepipelineRoleEDB68B98
  microservicepipelineSourceWebhookResource3E1D4E15:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: SECRET_TOKEN_HERE
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline:
        Ref: microservicepipelineD3929609
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true
  microservicepipelineBuildCodePipelineActionRole5183B64F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  microservicepipelineBuildCodePipelineActionRoleDefaultPolicy7290E65F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicebuilderEA0AB225
                - Arn
        Version: "2012-10-17"
      PolicyName: microservicepipelineBuildCodePipelineActionRoleDefaultPolicy7290E65F
      Roles:
        - Ref: microservicepipelineBuildCodePipelineActionRole5183B64F
  microservicepipelineDeployCodePipelineActionRole7CFFD997:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  microservicepipelineDeployCodePipelineActionRoleDefaultPolicy2527EB33:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicedeployer94899C23
                - Arn
        Version: "2012-10-17"
      PolicyName: microservicepipelineDeployCodePipelineActionRoleDefaultPolicy2527EB33
      Roles:
        - Ref: microservicepipelineDeployCodePipelineActionRole7CFFD997
  microservicedeployerRoleD3CA7605:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
  microservicedeployerRoleDefaultPolicy2F60A829:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicedeployer94899C23
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicedeployer94899C23
                    - :*
          - Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: microservicedeployer94899C23
                  - -*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - pipelines3bucket60FDE7F2
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - pipelines3bucket60FDE7F2
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: microservicedeployerRoleDefaultPolicy2F60A829
      Roles:
        - Ref: microservicedeployerRoleD3CA7605
  microservicedeployer94899C23:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - microservicedeployerRoleD3CA7605
          - Arn
      Source:
        BuildSpec: >-
          {
            "version": "0.2",
            "phases": {
              "build": {
                "commands": [
                  "aws ecs update-service --service spring-eureka-gallery --force-new-deployment",
                  "aws ecs update-service --service spring-eureka-server --force-new-deployment",
                  "aws ecs update-service --service spring-eureka-zuul --force-new-deployment",
                  "aws ecs update-service --service spring-eureka-auth --force-new-deployment"
                ]
              }
            }
          }
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      Name: microservice-deployer
  ecsaccesspolicy50603363:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ecs:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ecs-access-policy
      Roles:
        - Ref: microservicedeployerRoleD3CA7605
Outputs:
  springeurekaauthout:
    Value:
      Fn::GetAtt:
        - springeurekaauthrepo62035FE7
        - Arn
    Export:
      Name: spring-eureka-auth-out
  springeurekaserverout:
    Value:
      Fn::GetAtt:
        - springeurekaserverrepo1350F586
        - Arn
    Export:
      Name: spring-eureka-server-out
  springeurekazuulout:
    Value:
      Fn::GetAtt:
        - springeurekazuulrepo3CAF3D98
        - Arn
    Export:
      Name: spring-eureka-zuul-out
  springeurekagalleryout:
    Value:
      Fn::GetAtt:
        - springeurekagalleryrepoC474C0E2
        - Arn
    Export:
      Name: spring-eureka-gallery-out

