version: "3.8"

services:
  eureka:
    image: 885887105084.dkr.ecr.eu-west-1.amazonaws.com/spring-eureka-server:latest
    build: ./spring-eureka-server
    ports:
    - 8761:8761
    networks:
      - microspring
  zuul:
    image: 885887105084.dkr.ecr.eu-west-1.amazonaws.com/spring-eureka-zuul:latest
    build: ./spring-eureka-zuul
    ports:
      - 8762:8762
    networks:
      - microspring
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka:8761
      _JAVA_OPTIONS: "-Dlogging.level.org.springframework=DEBUG"
  auth:
    image: 885887105084.dkr.ecr.eu-west-1.amazonaws.com/spring-eureka-auth:latest
    build: ./spring-eureka-auth
    ports:
    - 9100:9100
    networks:
      - microspring
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka:8761
      _JAVA_OPTIONS: "-Dlogging.level.org.springframework=DEBUG"
  gallery:
    image: 885887105084.dkr.ecr.eu-west-1.amazonaws.com/spring-eureka-gallery:latest
    build: ./spring-eureka-gallery
    ports:
    - 8100:8100
    networks:
      - microspring
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka:8761
      _JAVA_OPTIONS: "-Dlogging.level.org.springframework=DEBUG"
networks:
  microspring:
