apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: default
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: main
          image: ${EUREKA_REPO}:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_HOST
              value: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway
  namespace: default
  labels:
    app: zuul-gateway
spec:
  selector:
    app: zuul-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8762
      targetPort: 8762
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-gateway
  namespace: default
  labels:
    app: zuul-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-gateway
  template:
    metadata:
      labels:
        app: zuul-gateway
    spec:
      containers:
        - name: main
          image: ${ZUUL_REPO}:latest
          ports:
            - containerPort: 8762
          env:
            - name: EUREKA_HOST
              value: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: main
          image: ${AUTH_REPO}:latest
          ports:
            - containerPort: 9100
          env:
            - name: EUREKA_HOST
              value: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: gallery-service
  namespace: default
  labels:
    app: gallery-service
spec:
  selector:
    app: gallery-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-service
  namespace: default
  labels:
    app: zuul-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery-service
  template:
    metadata:
      labels:
        app: gallery-service
    spec:
      containers:
        - name: main
          image: ${GALLERY_REPO}:latest
          ports:
            - containerPort: 8100
          env:
            - name: EUREKA_HOST
              value: eureka
