Resources:
  microservicebuilderRoleE267C15A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
  microservicebuilderRoleDefaultPolicy0ABB4B92:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicebuilderEA0AB225
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: microservicebuilderEA0AB225
                    - :*
          - Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: microservicebuilderEA0AB225
                  - -*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
                    - /*
        Version: "2012-10-17"
      PolicyName: microservicebuilderRoleDefaultPolicy0ABB4B92
      Roles:
        - Ref: microservicebuilderRoleE267C15A
  microservicebuilderEA0AB225:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - microservicebuilderRoleE267C15A
          - Arn
      Source:
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      Name: microservice-builder
  ecraccesspolicy1B6F6DE0:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ecr:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ecr-access-policy
      Roles:
        - Ref: microservicebuilderRoleE267C15A
  microservicepipelineRoleEDB68B98:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: "2012-10-17"
  microservicepipelineRoleDefaultPolicyFBAD8A8F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
                    - /*
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineBuildCodePipelineActionRole5183B64F
                - Arn
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineReplaceDeployDeleteCodePipelineActionRoleC7E3BC2E
                - Arn
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineReplaceDeployCodePipelineActionRoleEFE25C99
                - Arn
        Version: "2012-10-17"
      PolicyName: microservicepipelineRoleDefaultPolicyFBAD8A8F
      Roles:
        - Ref: microservicepipelineRoleEDB68B98
  microservicepipelineD3929609:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - microservicepipelineRoleEDB68B98
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: dmytrozzz
                Repo: microservices-spring-boot
                Branch: master
                OAuthToken: SECRET_TOKEN_HERE
                PollForSourceChanges: false
              Name: Source
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: microservicebuilderEA0AB225
                EnvironmentVariables:
                  Fn::Join:
                    - ""
                    - - '[{"name":"AUTH_REPO","type":"PLAINTEXT","value":"'
                      - Fn::ImportValue: spring-eureka-auth-uri
                      - '"},{"name":"EUREKA_REPO","type":"PLAINTEXT","value":"'
                      - Fn::ImportValue: spring-eureka-server-uri
                      - '"},{"name":"ZUUL_REPO","type":"PLAINTEXT","value":"'
                      - Fn::ImportValue: spring-eureka-zuul-uri
                      - '"},{"name":"GALLERY_REPO","type":"PLAINTEXT","value":"'
                      - Fn::ImportValue: spring-eureka-gallery-uri
                      - '"}]'
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build
              RoleArn:
                Fn::GetAtt:
                  - microservicepipelineBuildCodePipelineActionRole5183B64F
                  - Arn
              RunOrder: 1
          Name: Build
        - Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                StackName: ecs
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::GetAtt:
                    - microservicepipelineReplaceDeployDeleteRoleE6CB1D19
                    - Arn
                ActionMode: DELETE_ONLY
              Name: Delete
              RoleArn:
                Fn::GetAtt:
                  - microservicepipelineReplaceDeployDeleteCodePipelineActionRoleC7E3BC2E
                  - Arn
              RunOrder: 1
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                StackName: ecs
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::GetAtt:
                    - microservicepipelineReplaceDeployRole4226D969
                    - Arn
                ActionMode: REPLACE_ON_FAILURE
                TemplatePath: SourceArtifact::ecs.yml
              InputArtifacts:
                - Name: SourceArtifact
              Name: Deploy
              RoleArn:
                Fn::GetAtt:
                  - microservicepipelineReplaceDeployCodePipelineActionRoleEFE25C99
                  - Arn
              RunOrder: 2
          Name: ReplaceDeploy
      ArtifactStore:
        Location:
          Fn::ImportValue: pipeline-s3-bucket-name
        Type: S3
      Name: microservice-pipeline
    DependsOn:
      - microservicepipelineRoleDefaultPolicyFBAD8A8F
      - microservicepipelineRoleEDB68B98
  microservicepipelineSourceWebhookResource3E1D4E15:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: ef0b8b8bc9095864ad2a0dc01436a2b6aac95683
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline:
        Ref: microservicepipelineD3929609
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true
  microservicepipelineBuildCodePipelineActionRole5183B64F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  microservicepipelineBuildCodePipelineActionRoleDefaultPolicy7290E65F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicebuilderEA0AB225
                - Arn
        Version: "2012-10-17"
      PolicyName: microservicepipelineBuildCodePipelineActionRoleDefaultPolicy7290E65F
      Roles:
        - Ref: microservicepipelineBuildCodePipelineActionRole5183B64F
  microservicepipelineReplaceDeployDeleteCodePipelineActionRoleC7E3BC2E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  microservicepipelineReplaceDeployDeleteCodePipelineActionRoleDefaultPolicy929631E6:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: iam:PassRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineReplaceDeployDeleteRoleE6CB1D19
                - Arn
          - Action:
              - cloudformation:DeleteStack
              - cloudformation:DescribeStack*
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":cloudformation:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :stack/ecs/*
        Version: "2012-10-17"
      PolicyName: microservicepipelineReplaceDeployDeleteCodePipelineActionRoleDefaultPolicy929631E6
      Roles:
        - Ref: microservicepipelineReplaceDeployDeleteCodePipelineActionRoleC7E3BC2E
  microservicepipelineReplaceDeployDeleteRoleE6CB1D19:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
        Version: "2012-10-17"
  microservicepipelineReplaceDeployDeleteRoleDefaultPolicyBF73AF12:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
                    - /*
          - Action: "*"
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: microservicepipelineReplaceDeployDeleteRoleDefaultPolicyBF73AF12
      Roles:
        - Ref: microservicepipelineReplaceDeployDeleteRoleE6CB1D19
  microservicepipelineReplaceDeployCodePipelineActionRoleEFE25C99:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  microservicepipelineReplaceDeployCodePipelineActionRoleDefaultPolicyC447FD79:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: iam:PassRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - microservicepipelineReplaceDeployRole4226D969
                - Arn
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
                    - /*
          - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStack*
              - cloudformation:GetStackPolicy
              - cloudformation:GetTemplate*
              - cloudformation:SetStackPolicy
              - cloudformation:UpdateStack
              - cloudformation:ValidateTemplate
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":cloudformation:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :stack/ecs/*
        Version: "2012-10-17"
      PolicyName: microservicepipelineReplaceDeployCodePipelineActionRoleDefaultPolicyC447FD79
      Roles:
        - Ref: microservicepipelineReplaceDeployCodePipelineActionRoleEFE25C99
  microservicepipelineReplaceDeployRole4226D969:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
        Version: "2012-10-17"
  microservicepipelineReplaceDeployRoleDefaultPolicyD2A019E3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: pipeline-s3-bucket-name
                    - /*
          - Action: "*"
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: microservicepipelineReplaceDeployRoleDefaultPolicyD2A019E3
      Roles:
        - Ref: microservicepipelineReplaceDeployRole4226D969

