version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query 'repositories[*].repositoryUri'):$CODEBUILD_BUILD_NUMBER
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query 'repositories[*].repositoryUri'):latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query 'repositories[*].repositoryUri'):$CODEBUILD_BUILD_NUMBER
      - docker push $(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query 'repositories[*].repositoryUri'):latest
